version: '3'
services:

    #PHP Service
    app:
        container_name: laravel-kit-app
        build:
            context: .
            dockerfile: docker/Dockerfile-php8.0.2
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        extra_hosts:
            - "host.docker.internal:${HOST_IP}"
            - "www.laravel-kit-dev.io:${HOST_IP}"
        networks:
            - app-network

    #Nginx Service
    nginx:
        container_name: laravel-kit-nginx
        image: nginx:1.17
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        extra_hosts:
            - "host.docker.internal:${HOST_IP}"
            - "www.laravel-kit-dev.io:${HOST_IP}"
        networks:
            - app-network

    #MySQL Service
    database:
        container_name: laravel-kit-mysql
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        command:
          [
              "mysqld",
              "--default-authentication-plugin=mysql_native_password",
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_unicode_ci"
          ]
        environment:
            MYSQL_DATABASE: laravel_docker_kit
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./docker/database_data_dir:/var/lib/mysql
        extra_hosts:
            - "host.docker.internal:${HOST_IP}"
            - "www.laravel-kit-dev.io:${HOST_IP}"
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
